# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'

target 'DouBanMovie' do

pod 'AFNetworking', '~> 3.1.0'
pod 'Masonry', '~> 1.0.2'
pod 'MJExtension', '~> 3.0.13'
pod 'MJRefresh', '~> 3.1.12'
pod 'SDWebImage', '~> 4.1.0'
pod 'SVProgressHUD', '~> 2.1.2'
pod 'YYText', '~> 1.0.7'

end
